### ISSUE TITLE
Consider not polling by default

### ISSUE THREAD

**Issue by devinus** [elbuo8/sqs.js#1]
Allows more control over when to start polling. I can do this by setting `debug: true`, but that's disingenuous in my case.

**Comment by devinus** [comment]
...or renaming the `debug` option?

**Comment by elbuo8** [comment]
How would you name it?

**Comment by devinus** [comment]
Um, maybe `startPolling` or `immediatelyPoll` or something like that?

**Comment by elbuo8** [comment]
https://github.com/elbuo8/sqs.js/commit/61582897386aeb0d3acf5118132ba5d5f8ca6003
