### ISSUE TITLE
Immediately receive a message when polling starts (don't wait 1s for first message)

### ISSUE THREAD

**Issue by devinus** [elbuo8/sqs.js#2]
Perhaps just call the function here: https://github.com/elbuo8/sqs.js/blob/master/lib/reader.js#L78 ?

**Comment by elbuo8** [comment]
:+1: nice catch!

**Comment by elbuo8** [comment]
https://github.com/elbuo8/sqs.js/commit/70b49272f65a7084f4d33432f92678615a46c11e
